# Generated by Django 5.1.2 on 2024-12-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='equipment_ids',
            new_name='equipment_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='material_ids',
            new_name='material_id',
        ),
    ]
