# Generated by Django 5.1.2 on 2024-12-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_labour_allocated_labour_profession_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession_name', models.CharField(blank=True, max_length=255)),
                ('allocated', models.BooleanField(default=False)),
                ('units', models.CharField(max_length=100)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession')),
            ],
        ),
        migrations.DeleteModel(
            name='Labour',
        ),
    ]
