# Generated by Django 5.1.2 on 2024-12-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_labours_delete_labour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labours',
            new_name='Labour',
        ),
    ]
