# Generated by Django 5.1.2 on 2024-12-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_materials_delete_material_remove_labour_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
    ]
