# Generated by Django 5.1.2 on 2024-12-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_materials_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment_quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_quantity',
            field=models.CharField(max_length=255),
        ),
    ]
