# Generated by Django 5.1.2 on 2024-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_project_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='labour_ids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_quantity',
            field=models.IntegerField(),
        ),
    ]
