# Generated by Django 5.1.2 on 2024-12-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_project_equipment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='labour_ids',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_id',
            field=models.CharField(max_length=255),
        ),
    ]
