# Generated by Django 5.1.2 on 2024-12-14 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_project_equipment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('usage_quantity', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipment')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labour')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
