# Generated by Django 5.1.2 on 2024-12-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_resourceusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='equipment_id',
            new_name='equipment_ids',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='equipment_quantity',
            new_name='equipment_quantities',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='material_id',
            new_name='material_ids',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='material_quantity',
            new_name='material_quantities',
        ),
    ]
