# Generated by Django 5.1.2 on 2024-12-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_equipment_id_project_equipment_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceusage',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.equipment'),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='labour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.labour'),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.material'),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='usage_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
