# Generated by Django 5.1.2 on 2024-12-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_resourceusag_delete_resourceusage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceUsag',
            new_name='ResourceUsage',
        ),
    ]
